[[libdeflate]]
arch = "aarch64"
git-tree-sha1 = "7259a24061c70bb4ac63060009c436dabd331a2c"
os = "macos"

    [[libdeflate.download]]
    sha256 = "c0dedc9413d6e73f319daf882ce3903d8b0b918d1847f279b4b37b56dae1aa5c"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.aarch64-apple-darwin.tar.gz"
[[libdeflate]]
arch = "aarch64"
git-tree-sha1 = "2b02c7cdfca283709e59e63660ede89052ab7b02"
libc = "glibc"
os = "linux"

    [[libdeflate.download]]
    sha256 = "257389601c63622785f873ff6bebb1a47c2a5a6ab440a34f3f185ae6f86fe2a9"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.aarch64-linux-gnu.tar.gz"
[[libdeflate]]
arch = "aarch64"
git-tree-sha1 = "45d12bb37e6ad22cbf01223f1d9811528d1a6fe5"
libc = "musl"
os = "linux"

    [[libdeflate.download]]
    sha256 = "dd10214d9ad536abcb424e75885da0c4114b332e49ae7e6b803bd464ae51f533"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.aarch64-linux-musl.tar.gz"
[[libdeflate]]
arch = "aarch64"
git-tree-sha1 = "9f8a807b063068cdf7dc51859a84d6cd010bc96c"
os = "freebsd"

    [[libdeflate.download]]
    sha256 = "e242ff684e001f9304434051a8f5b2a437f3f65f1b9f483ac60be5be86029c50"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.aarch64-unknown-freebsd.tar.gz"
[[libdeflate]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "477db33cfece1ef9cc2b0d7d7ce9ee1ad896f630"
libc = "glibc"
os = "linux"

    [[libdeflate.download]]
    sha256 = "51707218e75ea63ed6a53097e3e1fbbe31b152ede9a38b098883d56487ae44d2"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.armv6l-linux-gnueabihf.tar.gz"
[[libdeflate]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0bbe34988b53de8e5f3ba29f5d6dcb6f74192b7c"
libc = "musl"
os = "linux"

    [[libdeflate.download]]
    sha256 = "6136a92c3c0ad6f9597efe834afe4d6d18bf3df059f23ddd2fe9382a0f6dfb05"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.armv6l-linux-musleabihf.tar.gz"
[[libdeflate]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "774b1c79f22d83ea1d583a6ef48b80e458e094e5"
libc = "glibc"
os = "linux"

    [[libdeflate.download]]
    sha256 = "da9e21471460b70c6f46dc3b8455a047c5c1813185389a6b5221f3ba84eb5cfb"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.armv7l-linux-gnueabihf.tar.gz"
[[libdeflate]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "419bde26db81f3000832cdafaca46343a095b312"
libc = "musl"
os = "linux"

    [[libdeflate.download]]
    sha256 = "f3fc8b587ba0090b265bed9fc8ad3ef966471ce78c66ccc7f7f7d7330b0ddc52"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.armv7l-linux-musleabihf.tar.gz"
[[libdeflate]]
arch = "i686"
git-tree-sha1 = "dd74485821d895c62d2bf40c39053150ab0221e2"
libc = "glibc"
os = "linux"

    [[libdeflate.download]]
    sha256 = "ba0b9be79b8be82f030fa7c329a4dd19e7d5dc213ad50c348207aedac72dc199"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.i686-linux-gnu.tar.gz"
[[libdeflate]]
arch = "i686"
git-tree-sha1 = "c424b689b39aaa5ac7aa97a8ef87e388ca70fb9d"
libc = "musl"
os = "linux"

    [[libdeflate.download]]
    sha256 = "c15a930bb36126886eeb8c8db648ddd9ce8503b573cc73c1d833c6aae5f3f932"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.i686-linux-musl.tar.gz"
[[libdeflate]]
arch = "i686"
git-tree-sha1 = "8268678ed7f17fa0af60232285ca2b2aa9a4e350"
os = "windows"

    [[libdeflate.download]]
    sha256 = "d899b049a203a93b286f7c81f7a1ff8dcd74addf1ed267c04344afc05913cc6f"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.i686-w64-mingw32.tar.gz"
[[libdeflate]]
arch = "powerpc64le"
git-tree-sha1 = "0935075b6937c18f1e9cf6ba443fbf039ee71330"
libc = "glibc"
os = "linux"

    [[libdeflate.download]]
    sha256 = "4f26fb82648cebf5fa0bdb96646d481faa1aa0dd19cd8cdf0e4253734e2dfc9f"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.powerpc64le-linux-gnu.tar.gz"
[[libdeflate]]
arch = "riscv64"
git-tree-sha1 = "8bd646bf847dda1068e98f75e4e7225230c00dd9"
libc = "glibc"
os = "linux"

    [[libdeflate.download]]
    sha256 = "43256d00aea349776d08793e08ce9a47a70115dd0a39fd0ee1f1fea2722da27a"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.riscv64-linux-gnu.tar.gz"
[[libdeflate]]
arch = "x86_64"
git-tree-sha1 = "2b26213dd077af7bf73b8077f86f7c4dbcb0a1dd"
os = "macos"

    [[libdeflate.download]]
    sha256 = "851176ecec302e848beff7b54e6d05be4cc7a2fc609f51799e016d321421be82"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.x86_64-apple-darwin.tar.gz"
[[libdeflate]]
arch = "x86_64"
git-tree-sha1 = "97e28666eab3536309e109ca285ccd3749bb46fa"
libc = "glibc"
os = "linux"

    [[libdeflate.download]]
    sha256 = "159de9af9c2ec46a64c09192d6fd97cd2ddc39d94bb5de80e3654582762b5641"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.x86_64-linux-gnu.tar.gz"
[[libdeflate]]
arch = "x86_64"
git-tree-sha1 = "ecaa8013ac276cf5cdb3caaed1183fedadf017af"
libc = "musl"
os = "linux"

    [[libdeflate.download]]
    sha256 = "8a8e452247f90a419904e6b5765a54f38e4ae98f2389fe6578f41660ff3dc1f2"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.x86_64-linux-musl.tar.gz"
[[libdeflate]]
arch = "x86_64"
git-tree-sha1 = "25d2a7b8a44b19c418dda5b1c2f04b67c8b269d7"
os = "freebsd"

    [[libdeflate.download]]
    sha256 = "806570efda171b56c86f78f0c07a69f71d86dfd192a3b244b6b9a9bb9eff048c"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.x86_64-unknown-freebsd.tar.gz"
[[libdeflate]]
arch = "x86_64"
git-tree-sha1 = "d92ec62700c48b74ff72321aef0efaf9b8276fc1"
os = "windows"

    [[libdeflate.download]]
    sha256 = "67388097ddb3a9f0742e5c229b0f61154c5775ce21eab1ca870f4aa45bf3eb66"
    url = "https://github.com/JuliaBinaryWrappers/libdeflate_jll.jl/releases/download/libdeflate-v1.25.0+0/libdeflate.v1.25.0.x86_64-w64-mingw32.tar.gz"
